# ----------------- Environmental & Paths -----------------
paths:
  dicom_studies: "/kaggle/input/rsna-2024-lumbar-spine-degenerative-classification/train_images"
  tfrecord: "/kaggle/working/lumbar_spine/tfrecords"
  output: "/kaggle/working/lumbar_spine/output/"
  checkpoint: "/kaggle/working/lumbar_spine/output/checkpoints"
  log_mirror: "/kaggle/working/lumbar_spine/output/logs/full_session_output.log"
  inspection: "/kaggle/working/lumbar_spine/input_data_inspection/"
  csv:
    description: "/kaggle/input/rsna-2024-lumbar-spine-degenerative-classification/train_series_descriptions.csv"
    label_coordinates: "/kaggle/input/rsna-2024-lumbar-spine-degenerative-classification/train_label_coordinates.csv"
    train: "/kaggle/input/rsna-2024-lumbar-spine-degenerative-classification/train.csv"

# ----------------- Data Engineering ----------------------
data_specs:
  series_depth_percentile: 95
  slices_input_format: [640, 640, 1]
  max_records_per_frame: 25
  dataset_buffer_size_mb: 100

# ----------------- Model Architectures -------------------
models:
  backbone_2d:
    type: "MobileNetV2"
    img_shape: [224, 224, 3]
    scaling: { max: 1, min: -1 }
  head_3d:
    type: "cnn3d"
    input_shape: [7, 7, 1280]
    filters: 64

# ----------------- Training & Compilation ----------------
training:
  hyperparameters:
    train_split_ratio: 0.8
    batch_size: 3
    epochs: 10
    patience: 5
    learning_rate: 0.0001
    clipnorm: 1.0
    resume_mode: last # 2 modes: "best" or "last" 
  
  compilation:
    loss_weights:
      severity_output: 1.0
      location_output: 30.0
    run_eagerly: False

# ----------------- Hardware & Maintenance ----------------
system:
  nb_cores: 0  # 0 = all cores
  log_retention_days: 30


