# ----------------- Environmental & Paths -----------------
paths:
  dicom_studies: "/kaggle/input/competitions/rsna-2024-lumbar-spine-degenerative-classification/train_images"
  tfrecord: "/kaggle/working/lumbar_spine/tfrecords"
  output: "/kaggle/working/lumbar_spine/output/"
  checkpoint: "/kaggle/working/lumbar_spine/output/checkpoints"
  log_mirror: "/kaggle/working/lumbar_spine/output/logs/full_session_output.log"
  tf_cache: "/tmp/tensorflow_cache/lumbar_train"
  inspection: "/kaggle/working/lumbar_spine/input_data_inspection/"
  csv:
    series_description: "/kaggle/input/competitions/rsna-2024-lumbar-spine-degenerative-classification/train_series_descriptions.csv"
    label_coordinates: "/kaggle/input/competitions/rsna-2024-lumbar-spine-degenerative-classification/train_label_coordinates.csv"
    train: "/kaggle/input/competitions/rsna-2024-lumbar-spine-degenerative-classification/train.csv"
    instances_series_format: "/kaggle/working/csv_file/train_train_instances_series_format.csv"

# ----------------- Data Engineering ----------------------
data_specs:
  series_depth_percentile: 95
  max_records_per_frame: 25
  dataset_buffer_size_mb: 100

# ----------------- Model Architectures -------------------
models:
  backbone_2d:
    type: "MobileNetV2"
    img_shape: [224, 224, 3]
    freeze: True
    scaling: { min: -1.0, max: 1.0 }

  head_3d:
    type: "cnn3d"
    filters: 64

# ----------------- Training & Compilation ----------------
training:
  batch_size: 1
  epochs: 4
  train_split_ratio: 0.8
  # Metadata for the dynamic loss balancing strategy
  loss_balancer:
    momentum: 0.5        # Inertia factor (0.5 = balanced, 0.9 = very stable)
    min_weight: 0.5      # Minimum multiplier for location loss
    max_weight: 15.0     # Maximum multiplier for location loss

optimizer:
  type: adam
  learning_rate: 0.0001
  clipnorm: 1.0

callbacks:
  patience: 5
  resume_mode: last # 2 modes: "best" or "last" 

compilation:
  # Initial weights for Epoch 1. These will be updated dynamically 
  # by the LossBalancerCallback after each epoch.
  loss_weights:
    severity_output: 1.0
    location_output: 10.0
  run_eagerly: False

# ----------------- Hardware & Maintenance ----------------
system:
  nb_cores: 4  # 0 = all cores
  log_retention_days: 30
  seed: 42
  memory_threshold_percent: 90
  chunksize: 50 # 50 for HDD. 500 is acceptable for SSD

# -------------------- Dataset steering -------------------
# Steering values: 1 unit = 1 full TFRecord file (1 patient study)
dataset_steering:
  interleave:
    parallel_files: 1       # Equivalent to cycle_length
    block_per_file: 1       # 1 means the entire file is read before switching
    deterministic: False
  
  # How many patient studies to group before 3D reconstruction
  # (Usually 1, as 1 TFRecord already contains 1 full study)
  group_studies: 1          
  
  # Number of final training batches to keep in the pipeline buffer
  prefetch_batches: 1

  # Use -1 for tf.data.AUTOTUNE
  num_parallel_calls: 1

  # Use the cache or not
  use_cache: False

#--- Actual series depth (do not confuse with the percentile) --
# series_depth: config['series_depth'] is defined dynamically by the class ConfigLoader.

# ----------------- Logging & Debugging -------------------
logging:
  # Level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  # No other value is allowed
  level: "DEBUG"

  # Whether to display logs in the terminal
  console_display: False
  
  # Use JSON formatting for structured logs
  use_json: False
